FROM ncbi/edirect:latest AS edirect
FROM ncbi/sra-tools:latest AS sra-tools
FROM ncbi/blast:latest AS blast

# Final stage: Base image as Ubuntu 20.04
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

COPY --from=edirect /usr/local/ncbi/edirect /usr/local/ncbi/edirect
COPY --from=sra-tools /usr/local/bin /usr/local/bin
COPY --from=sra-tools /lib /lib
COPY --from=blast /blast/bin /blast/bin
COPY --from=blast /blast/lib /blast/lib

ENV PATH="/blast/bin:/usr/local/ncbi/edirect:${PATH}"
ENV LD_LIBRARY_PATH="/blast/lib:${LD_LIBRARY_PATH}"

RUN apt-get -y -qq update
RUN apt-get -y -qq --no-install-recommends install bash libxml2-utils perl libio-socket-ssl-perl libhtml-parser-perl libwww-perl libxml-simple-perl curl gzip make libgomp1 liblmdb0 cpanminus && \
    cpanm LWP::Protocol::https && \
    rm -rf /var/lib/apt/lists/* /root/.cpanm/*

COPY main.sh /main.sh
COPY samples.sh /samples.sh
COPY db.sh /db.sh
COPY rice.txt /rice.txt
COPY kidney.txt /kidney.txt

RUN chmod +x /main.sh /samples.sh /db.sh
