FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y -qq update
RUN apt-get -y -qq --no-install-recommends install git build-essential nano curl vim wget iperf3 traceroute iputils-ping ca-certificates gnupg2
RUN echo "deb [arch=amd64 trusted=yes] https://nfd-nightly-apt.ndn.today/ubuntu focal main" | tee /etc/apt/sources.list.d/nfd-nightly.list
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
RUN apt-get -y -qq update
RUN apt-get -y -qq --no-install-recommends install -f ndn6-tools
RUN rm -rf /var/lib/apt/lists/*
RUN mkdir -p /etc/ndn
RUN mkdir -p /fileserver_data
RUN echo "transport=unix:///run/nfd.sock" > /etc/ndn/client.conf