kind: Service
apiVersion: v1
metadata:
  name: gw
  namespace: ndnk8s
spec:
  type: NodePort
  selector:
    app: gw
  ports:
    - port: 6363
      targetPort: 6363
      protocol: UDP
      nodePort: 30007

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-service-account
  namespace: ndnk8s

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ndnk8s
  name: gateway-job-manager-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-job-manager-rolebinding
  namespace: ndnk8s
subjects:
  - kind: ServiceAccount
    name: gateway-service-account
    namespace: ndnk8s
roleRef:
  kind: Role
  name: gateway-job-manager-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw
  namespace: ndnk8s

spec:
  replicas: 1
  selector:
    matchLabels:
      app: gw
  template:
    metadata:
      labels:
        app: gw
    spec:
      volumes:
        - name: run-ndn
          hostPath:
            path: /run
        - name: ndn-log
          hostPath:
            path: /var/log/ndn
        - name: ndn-config
          hostPath:
            path: /root/.ndn
        - name: fileserver-data
          persistentVolumeClaim:
            claimName: datalake-storage-claim
      containers:
        - name: router
          image: sankalpatimilsina/ndn-tools:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["SYS_PTRACE"]
          volumeMounts:
            - mountPath: /run
              name: run-ndn
            - mountPath: /var/log/ndn
              name: ndn-log
            - mountPath: /root/.ndn
              name: ndn-config
          env:
            - name: CONFIG
              value: /etc/ndn/nfd.conf
            - name: LOG_FILE
              value: /var/log/ndn/nfd.log
          terminationMessagePath: /var/log/ndn/nfd.log
          command: ["/bin/bash"]
          args:
            [
              "-c",
              "nfd --config $(CONFIG) > $(LOG_FILE) 2>&1 & tail -f /dev/null",
            ]
        - name: gateway-app
          image: sankalpatimilsina/gateway:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["SYS_PTRACE"]
          volumeMounts:
            - mountPath: /run
              name: run-ndn
            - mountPath: /var/log/ndn
              name: ndn-log
            - mountPath: /root/.ndn
              name: ndn-config
            - mountPath: /fileserver_data
              name: fileserver-data
          env:
            - name: CONFIG
              value: /etc/ndn/nfd.conf
            - name: LOG_FILE
              value: /var/log/ndn/nfd.log
          terminationMessagePath: /var/log/ndn/nfd.log
          command: ["/bin/bash", "-c"]
          args: ["python -m app.gateway"]
          # args: ["sleep infinity"]
