FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y -qq update
RUN apt-get -y -qq --no-install-recommends install git build-essential nano \
    curl vim wget iperf3 traceroute iputils-ping ca-certificates gnupg2 \
    python3.8 python3-pip python3-venv

# Create virtual environment and activate
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Install Python dependencies
COPY requirements.txt .
RUN pip3 install -r requirements.txt

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app
COPY *.py /app
WORKDIR /app